### ISSUE TITLE
Any plans to allow order models by visit count?

### ISSUE THREAD

**Issue by selfpaidinc** [cyrildewit/laravel-page-visits-counter#11]
Great package, easy to integrate. I'm wondering if you have any plans to allow ordering model items by visit count? 

being able to order by total visits as well as 24h, 7d and 14d would be great.

**Comment by cyrildewit** [comment]
Good to know that you like this package and that it was easy to install. No, I didn't had any plans. But know I will make them ;).

I actually already have built this functionality inside a Laravel App (local development). This is the code that I'm using:

```
public function getMostPopularTopicsOfLast24Hours()
    {
        $topics = $this->_model->where('status', 'publish')->get();

        foreach ($topics as $topic) {
            $topic_courses = $this->courseRepository->getRecentCreatedCoursesBySubject($topic->slug);
            $topic->totalCourseVisitsOfLast24Hours = 0;

            foreach ($topic_courses as $topic_course) {
                $topic->totalCourseVisitsOfLast24Hours += $topic_course->last_24h_visits_count->number;
            }
        }

        $result = $topics->sortBy(function ($model) {
            return $model->totalCourseVisitsOfLast24Hours;
        })->reverse();

        return $result;
    }
```

The function will sort the available (status = publish) topics by most visited courses in the last 24 hours. It is not ready for production, because I think it is very slow. But it gets the job done.

I'm going to think about a flexible solution for this. If you got some ideas about it, please be my guest.

**Comment by cyrildewit** [comment]
Hi, quick update:

I made some breaking changes! That's why this package is stil under v1.0.0.

What you can do as described in the README.md, is using the sortBy method on a collection.
Here's an example:
```php
$articles = Article::all()->sortBy('page_visits_14d');
$articles = Article::with('relatedModel')->get()->sortBy('page_visits_7d');
$articles = Article::where('status', 'published')->get()->sortBy('page_visits_24h');
```

ps: don't forget to run `composer update`
